export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const FETCHING_PROFILE = 'FETCHING_PROFILE';
export const TOGGLE_LOADING = "TOGGLE_LOADING";
export const SAVE_LANGUAGE = "SAVE_LANGUAGE";

export const FETCH_PROFILE = 'FETCH_PROFILE';
export const SET_PROFILE = 'SET_PROFILE';